### ISSUE TITLE
The big rewrite

### ISSUE THREAD

**Issue by mymakerofficial** [mymakerofficial/time-companion#96]
#### TODO
- #92 
- #98 
- ~~#100~~
- [ ] Implement existing features
  - [x] Projects
  - [ ] Tasks
  - [x] Recording Time Entries
  - [ ] Calculating Worktime
  - [ ] Store user settings
- [x] Implement Database
  - [x] Use sqlite-wasm for the browser
  - [x] Use better-sqlite3 for node env's
  - [x] Use drizzle
  - [x] Implement Migrations
- [x] Clean-up
  - [ ] Remove Pinia
  - [ ] Remove js-joda
  - [ ] Remove redundant renderer libs
  - [ ] Remove redundant composables
